trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: |
    yarn -v
    yarn
    yarn run generate
  displayName: 'generate grammar'
  
- script: |
    yarn run test
  displayName: 'Run unit tests'